on:
  push:
    branches:
      - dev

jobs:
  push_dev_to_registry:
    name: Push dev image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push dev image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tenasi/plexannouncer:dev